# General
daemon=300      # check every 5 minutes
syslog=yes      # log update results
use=web, web=checkip.dyndns.com/ # use external web service to find ip

# Porkbun
protocol=porkbun
apikey=PORKBUN_API_KEY_PLACEHOLDER
secretapikey=PORKBUN_SECRET_KEY_PLACEHOLDER
DOMAIN_PLACEHOLDER,v1.DOMAIN_PLACEHOLDER,git.DOMAIN_PLACEHOLDER
